### ISSUE TITLE
figure request for additional years

### ISSUE THREAD

**Issue by liz-dawson-NOAA** [afsc-gap-products/coldpool#22]
While working on the [Bering Sea Tech Memos for 2018 and 2019](https://github.com/EmilyMarkowitz-NOAA/gap_bs_data_report), Em and I realized we need the following figures to include data only through the year of each tech memo: [average_temperature](https://github.com/afsc-gap-products/coldpool/blob/main/plots/average_temperature.png), [stacked_temperature](https://github.com/afsc-gap-products/coldpool/blob/main/plots/stacked_temperature.png), and [stacked_temperature_simple_label](https://github.com/afsc-gap-products/coldpool/blob/main/plots/stacked_temperature_simple_label.png). Cropping the stacked_temperature plots is theoretically easy (for example, I did a hack job with GIMP on the stacked plots for [2018](https://github.com/EmilyMarkowitz-NOAA/gap_bs_data_report/blob/main/img/stacked_temperature_simple_label_2018.png) and [2019](https://github.com/EmilyMarkowitz-NOAA/gap_bs_data_report/blob/main/img/stacked_temperature_simple_label_2019.png)), but the average_temperature plots will have different long-term (grand) mean temperature dashed lines in 2018 and 2019 than in 2021, so not easily just cropped down.  Could you run the three figures above for 2018 and 2019?  The 2021 figure are already made AND BEAUTIFUL!
Thank you, Sean!

**Comment by sean-rohan-NOAA** [comment]
I updated 1_cold_pool_index.Rmd to allow users to specify the maximum year to be used in figures. You'll just need to specify a different value for [max_year on Line 24](https://github.com/afsc-gap-products/coldpool/blob/a8e3db6188b0c0b3261796c42f13c531f323dfa7/1_cold_pool_index.Rmd#L24), and knit once for every year to produce the full compliment of figures.

Th figures below are the multi-panel cold pool temperatures + area figures for max_year = 2019 and max_year = 2021:
![2019_coldpool_with_area](https://user-images.githubusercontent.com/65584161/149587583-aba908bd-bad4-4c27-8eab-d74727f9d5a4.png)
![2021_coldpool_with_area](https://user-images.githubusercontent.com/65584161/149587585-84e0af6d-ed4d-4b5f-ab56-80849af9a67c.png)
