### ISSUE TITLE
update with 2022 data

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [afsc-gap-products/coldpool#32]
I hear that the temperature data have been QA/QC'd for this year.  We need to compute all metrics for 2022 by the time the catch data are QA/QC'd so we can use this as an input to the abundance index models.

**Comment by sean-rohan-NOAA** [comment]
Agreed, but this can't happen until the data are in the racebase haul table. It'll take a couple of hours to run when everything is finalized.

**Comment by sean-rohan-NOAA** [comment]
Yep, already been pestering folks about dates for the last couple of weeks.
